=== PomeloBounties/supported-networks/schemas/network.schema.json
{
  "$id": "https://thegraph.com/schemas/v1/network.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "description": "The Graph networks registry entry",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$",
      "description": "Established name of the chain on the Graph network, i.e. mainnet, btc, arweave-mainnet, near-testnet"
    },
    "displayName": {
      "type": "string",
      "description": "Display name of the network, i.e. Ethereum Mainnet, Bitcoin Testnet"
    },
    "caip2ChainId": {
      "type": "string",
      "pattern": "^[-a-z0-9]{3,8}:[-_a-zA-Z0-9]{1,32}$",
      "description": "CAIP-2 Chain ID, i.e. eip155:1, bip122:000000000019d6689c085ae165831e93"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-z0-9-]+$"
      },
      "description": "[optional] List of possible aliases for the chain, i.e. ethereum, eth, mainnet, eth-mainnet"
    },
    "childOf": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$",
      "description": "[optional] Name of the related L1 chain, i.e. mainnet"
    },
    "firehoseBlock": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9.]+$",
          "description": "Block type, i.e. sf.ethereum.type.v2.Block"
        },
        "bytesEncoding": {
          "type": "string",
          "enum": ["hex", "0xhex", "base58"],
          "description": "Bytes encoding, i.e. hex, 0xhex, base58"
        },
        "bufBuildUrl": {
          "type": "string",
          "format": "uri",
          "description": "Protobuf definitions on buf.build, i.e. https://buf.build/streamingfast/firehose-ethereum"
        },
        "evmModel": {
          "type": "string",
          "enum": ["base", "extended"],
          "description": "[optional] Block model if EVM chain, i.e. base or extended"
        }
      },
      "required": ["type", "bytesEncoding", "bufBuildUrl"],
      "additionalProperties": false,
      "description": "Firehose block information"
    },
    "genesisBlock": {
      "type": "object",
      "properties": {
        "hash": {
          "type": "string",
          "description": "Hash of the genesis block"
        },
        "height": {
          "type": "integer",
          "description": "Block height of the genesis block"
        }
      },
      "required": ["hash", "height"],
      "additionalProperties": false
    },
    "nativeToken": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9]+$",
      "description": "Symbol of the native token"
    },
    "graphNodeProtocol": {
      "type": "string",
      "enum": ["ethereum", "near", "arweave", "cosmos", "starknet"],
      "description": "[optional] Protocol name in graph-node, i.e. ethereum, near, arweave"
    },
    "blockExplorerUrls": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      },
      "description": "URLs for the block explorers"
    },
    "isTestnet": {
      "type": "boolean",
      "description": "Whether the chain is a testnet"
    },
    "studioSupport": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["subgraph-rpc", "subgraph-firehose", "subgraph-substreams"]
      },
      "description": "Chain support in Edge&Node Studio"
    },
    "issuanceRewards": {
      "type": "boolean",
      "description": "Issuance rewards on the Graph Network for this chain"
    },
    "web3Icon": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "publicRpcUrls": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      },
      "description": "List of public RPC URLs for the chain"
    },
    "publicApiUrls": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      },
      "description": "List of public API URLs for the chain, i.e. https://api.etherscan.io/api"
    },
    "docsUrl": {
      "type": "string",
      "format": "uri",
      "description": "URL to the chain documentation"
    }
  },
  "required": [
    "name",
    "caip2ChainId",
    "displayName",
    "blockExplorerUrls",
    "publicApiUrls",
    "isTestnet",
    "studioSupport",
    "issuanceRewards",
    "nativeToken",
    "publicRpcUrls"
  ],
  "additionalProperties": false,

  "if": {
    "properties": {
      "caip2ChainId": {
        "pattern": "^eip155:"
      }
    }
  },
  "then": {
    "properties": {
      "firehoseBlock": {
        "required": ["evmModel"]
      }
    }
  },
  "else": {
    "properties": {
      "firehoseBlock": {
        "properties": {
          "evmModel": false
        }
      }
    }
  }
}

=== PomeloBounties/supported-networks/registry/networks/antelope/eos.json
{
  "name": "eos",
  "displayName": "EOS",
  "aliases": ["eos-mainnet"],
  "caip2ChainId": "antelope:aca376f206b8fc25a6ed44dbdc66547c",
  "blockExplorerUrls": [
    "https://bloks.io/"
  ],
  "publicRpcUrls": [
    "https://eos.api.eosnation.io/"
  ],
  "publicApiUrls": [],
  "isTestnet": false,
  "studioSupport": [],
  "issuanceRewards": false,
  "nativeToken": "EOS",
  "docsUrl": "https://docs.eosnetwork.com/docs/latest/quick-start/introduction",
  "web3Icon": "eos",
  "genesisBlock": {
    "hash": "0000000267f3e2284b482f3afc2e724be1d6cbc1804532ec62d4e7af47c30693",
    "height": 2
  },
  "firehoseBlock": {
    "type": "sf.antelope.type.v1.Block",
    "bufBuildUrl": "https://buf.build/pinax/firehose-antelope",
    "bytesEncoding": "hex"
  }
}

=== PomeloBounties/supported-networks/registry/networks/cosmos/injective-mainnet.json
{
  "name": "injective-mainnet",
  "displayName": "Injective",
  "aliases": ["injective", "injective-1"],
  "caip2ChainId": "cosmos:injective-1",
  "blockExplorerUrls": [
    "https://explorer.injective.network/"
  ],
  "publicRpcUrls": [],
  "publicApiUrls": [],
  "isTestnet": false,
  "studioSupport": [],
  "issuanceRewards": false,
  "nativeToken": "INJ",
  "docsUrl": "https://docs.injective.network/",
  "web3Icon": "injective",
  "genesisBlock": {
    "hash": "24c9714291a999b952859ee02ec9b233394fe743b07ea3578d432a4a2707b6af",
    "height": 1
  },
  "firehoseBlock": {
    "type": "sf.cosmos.type.v2.Block",
    "bufBuildUrl": "https://buf.build/streamingfast/firehose-cosmos",
    "bytesEncoding": "hex"
  }
}

=== PomeloBounties/supported-networks/registry/networks/antelope/kylin.json
{
  "name": "kylin",
  "displayName": "Kylin",
  "aliases": ["kylin"],
  "caip2ChainId": "antelope:5fff1dae8dc8e2fc4d5b23b2c7665c97",
  "blockExplorerUrls": [
    "https://kylin.bloks.io/"
  ],
  "publicRpcUrls": [
    "https://kylin.api.eosnation.io/"
  ],
  "publicApiUrls": [],
  "isTestnet": true,
  "studioSupport": [],
  "issuanceRewards": false,
  "nativeToken": "EOS",
  "docsUrl": "https://docs.eosnetwork.com/docs/latest/quick-start/introduction",
  "web3Icon": "eos",
  "genesisBlock": {
    "hash": "00000002a1ec7ae214b9e43a904b6c010fb1260c9e8a12e5967bdbe451152a07",
    "height": 2
  },
  "firehoseBlock": {
    "type": "sf.antelope.type.v1.Block",
    "bufBuildUrl": "https://buf.build/pinax/firehose-antelope",
    "bytesEncoding": "hex"
  }
}

=== PomeloBounties/supported-networks/registry/networks/near/near-mainnet.json
{
  "name": "near-mainnet",
  "displayName": "Near",
  "aliases": ["near"],
  "caip2ChainId": "near:mainnet",
  "blockExplorerUrls": [
    "https://nearblocks.io/"
  ],
  "publicRpcUrls": [
    "https://rpc.mainnet.near.org"
  ],
  "publicApiUrls": [],
  "isTestnet": false,
  "studioSupport": [],
  "issuanceRewards": false,
  "nativeToken": "NEAR",
  "docsUrl": "https://docs.near.org/",
  "web3Icon": "near",
  "genesisBlock": {
    "hash": "a7110b9052e1be68f7fa8bb4065bf54e731205801878e708db7464ec4b9b8014",
    "height": 9820214
  },
  "firehoseBlock": {
    "type": "sf.near.type.v1.Block",
    "bufBuildUrl": "https://buf.build/streamingfast/firehose-near",
    "bytesEncoding": "hex"
  }
}
